### ISSUE TITLE
Internationalization: No UTF-8 support

### ISSUE THREAD

**Issue by quirysse** [LASzip/LASzip#16]
Current library status does not support internationalized characters. 

This could be done without API change by accepting laszip_CHAR\* as a UTF-8 encoded string or with an API addition introducing something like laszip_WCHAR\* type and new calls like laszip_open_writer_widechar.

**Comment by hobu** [comment]
:+1: to UTF-8

I'm not as excited about wide characters with requisite API changes.

**Comment by quirysse** [comment]
I totally agree with @hobu and I too prefer the UTF-8 solution (http://utf8everywhere.org/).

However, I would be happy with any solution as long as I can get rid of the cumbersome user code needed to overcome this limitation (like renaming files after creation, or using non-portable tricks to get "Short Path Name" on Windows).

**Comment by rapidlasso** [comment]
I have a similar request from Trimble and currently they use their own work-around. How about we add a function that tells the api that the const char* really points to a string of two-byte wide characters and leave the current interface intact otherwise:

LASZIP_API laszip_I32
laszip_file_name_is_wide_char(
    laszip_POINTER                     pointer
    , const laszip_BOOL               is_wide
);

**Comment by quirysse** [comment]
One major advantage of UTF-8 over wide-char is that it doesn't need any API change at all and is backward compatible with existing implementations. 

Also wide-char may vary in size from 2 bytes on MSVCPP, up to 4 bytes on gcc which makes it cumbersome to use in an API that supports a broad range of platforms. 

UTF-8 most likely does not require any changes on linux-like platforms, and would only require a conversion from UTF-8 to wide-char on Windows before calling **fopen** (would actually be **_wfopen** for that matter).

**Comment by hobu** [comment]
I also think it would be a mistake to spread wide character stuff all over the interface. What is the reason that Trimble can't use UTF-8?

I would note that unless it is very Windows-centric, most APIs don't do wide character stuff in their APIs. This is very much true in the open source GIS space, where UTF-8 is assumed and conversion is done to make things play well.

**Comment by quirysse** [comment]
I was actually speaking on behalf of Trimble: **Trimble does favor UTF-8** as well. I think the wide-char option was simply a suggestion from @rapidlasso (just my guess).

**Comment by rapidlasso** [comment]
I was not suggesting any particular implementation. I was asking about what the best way ould be to add internationalization to the API. I was given a code sample from Trimble that works with wide-char and assumed that would be the way to do it. But I am just as happy with UTF-8 if that is better. Yet my question remains the same. Can we simply leave the interface as it is and add a function

LASZIP_API laszip_I32
laszip_file_name_is_utf8(
laszip_POINTER pointer
, const laszip_BOOL is_utf8
);

that will - if set TRUE - interpret the const char* given to the API via the open function as an utf8 encoded file name instead of a plain ASCII string. Seems to me that would be the way to go ... ?

**Comment by quirysse** [comment]
I am not sure that the additional function is necessary because UTF-8 is compatible with plain ASCII: plain ASCII characters have the exact same representation in UTF-8. 

Libraries supporting UTF-8 usually don't need any extra function to trigger it. E.g: [ASTM e57](http://www.libe57.org/requirements.html#_Toc195489760) (to remain in the point cloud)

**Comment by rapidlasso** [comment]
The handling of UFT-8 / unicode under Windows was added in these commits https://github.com/LASzip/LASzip/commit/ac1921a89a0f15e61e58df9cde5477fabad0241c https://github.com/LASzip/LASzip/commit/ee8a0d94de07a800689dff0730b6ea0475dbf2ba but there was one report about this causing problems for Finnish file names. This should be opened as a new issue, though.
