### ISSUE TITLE
Does laszip_api.c support extended vlrs?

### ISSUE THREAD

**Issue by gadomski** [LASzip/LASzip#35]
A quick pan through https://github.com/LASzip/LASzip/blob/master/dll/laszip_api.c doesn't turn up any `evlr` references. Does `laszip_api.c` support extended variable length records? The `laszip_set_header` method allows the setting of vlrs, but the vlr length is constrained to a `i16`.

**Comment by gadomski** [comment]
After an offline discussion, it appears that the answer is no. The C API supports generic VLRs but not EVLRs.

**Comment by rapidlasso** [comment]
Indeed. I guess that I never added this part because I did not need it yet (and I did not want to encourage folks writing EVLRs unless absolutely needed). EVLRs should only really be used when you have very big payloads. For example, when you use EVLRs then you can no longer do any streaming operations on the file whenever you use compression or whenever you filtering / deleting an unknown number of points. Command-line piping of modules no longer works. Also any operation performing some form of piped re-projecting will not work if you store the CRS as a EVLR as the tool won't know what the source projection was until the entire stream was read to the end.

**Comment by gadomski** [comment]
Understood, thanks!
