### ISSUE TITLE
3.2.1 tarball named 3.2.0

### ISSUE THREAD

**Issue by ilovezfs** [LASzip/LASzip#44]
https://github.com/LASzip/LASzip/releases/download/3.2.1/laszip-src-3.2.0.tar.bz2

**Comment by hobu** [comment]
I'm sorry. I copied the wrong files. I will fix ASAP.

**Comment by hobu** [comment]
after some investigation, I forgot to increment a version number. I will issue 3.2.2 😦 today. Practice makes perfect.

**Comment by hobu** [comment]
please try https://github.com/LASzip/LASzip/releases/tag/3.2.2 now.

**Comment by ilovezfs** [comment]
Voilà https://github.com/Homebrew/homebrew-core/pull/25831

Thanks @hobu!

**Comment by ryandesign** [comment]
Thanks! https://github.com/macports/macports-ports/pull/1489

**Comment by hobu** [comment]
Sorry I'm such a lame release manager. We need to get more of this push-button. Part of the problem is this codebase is derived from LAStools and so the scaffolding around it isn't quite the same. 

Expect a 4.0.0 release when @rapidlasso is ready to flip the switch on the V4 LAZ writing in the future.

**Comment by rapidlasso** [comment]
Thank you @hobu. Your effort in managing the LASzip releases is highly appreciated.
